name: Build Manager

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'manager/**'
  workflow_call:

jobs:
  build-ksud:
    strategy:
      matrix:
        include:
          - target: armv7-linux-androideabi
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}

  build-manager:
    needs: build-ksud
    runs-on: ubuntu-latest
    environment: APK_SIGN
    defaults:
      run:
        working-directory: ./manager

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup need_upload
        id: need_upload
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            echo "UPLOAD=true" >> $GITHUB_OUTPUT
          else
            echo "UPLOAD=false" >> $GITHUB_OUTPUT
          fi

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' >> gradle.properties
            echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}' >> gradle.properties
            echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo KEYSTORE_FILE='../key.jks' >> gradle.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Download arm ksud
        uses: actions/download-artifact@v4
        with:
          name: ksud-armv7-linux-androideabi
          path: .

      - name: Copy ksud to app jniLibs
        run: |
          mkdir -p app/src/main/jniLibs/armeabi-v7a
          cp -f ../armv7-linux-androideabi/release/ksud ../manager/app/src/main/jniLibs/armeabi-v7a/libksud.so

      - name: Build with Gradle
        run: |
          {
            echo 'org.gradle.parallel=true'
            echo 'org.gradle.vfs.watch=true'
            echo 'org.gradle.jvmargs=-Xmx2048m'
            echo 'android.native.buildOutput=verbose'
          } >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          ./gradlew clean assembleRelease

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: manager
          path: manager/app/build/outputs/apk/release/*.apk
